require("Goose.set")
require("Goose.remap")
require("Goose.treesitter_conf")
require("Goose.telescope")
require("Goose.comment")
require("Goose.lsp")
require("Goose.cmp")
require("Goose.fterm")
print("Loaded Goose config")
