require("Goose.set")
require("Goose.remap")
require("Goose.treesitter")
require("Goose.telescope")
require("Goose.comment")
require("Goose.mason")
require("Goose.cmp")
-- require("Goose.fterm")
require("Goose.tree")
-- require("Goose.lualine")
-- require("Goose.barbar")
require("Goose.workspaces")
print("Loaded Goose config")
