require("Goose.set")
require("Goose.remap")
require("Goose.treesitter")
require("Goose.telescope")
require("Goose.comment")
require("Goose.lsp")
require("Goose.cmp")
require("Goose.fterm")
require("Goose.tree")
require("Goose.lualine")
require("Goose.barbar")
require("Goose.project")
print("Loaded Goose config")
